# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

plugin_name: pulp_gem
plugin_app_label: gem
plugin_snake: pulp_gem
plugin_caps: PULP_GEM
plugin_caps_short: GEM
plugin_camel: PulpGem
plugin_camel_short: Gem
plugin_dash: pulp-gem
plugin_dash_short: gem
black: True
check_commit_message: False
coverage: False
deploy_client_to_pypi: False
deploy_client_to_rubygems: False
deploy_daily_client_to_pypi: False
deploy_daily_client_to_rubygems: False
deploy_to_pypi: False
docs_test: True
pydocstyle: True
test_bindings: False
pypi_username: None
travis_notifications: None


